# Generated by Django 5.1.5 on 2025-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoya', '0002_remove_restaurant_price_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
