# Generated by Django 5.1.5 on 2025-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoya', '0004_remove_restaurant_cuisine_type_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
    ]
