# Generated by Django 5.1.5 on 2025-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoya', '0005_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closed_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
